import { StyleSheet } from 'react-native';
import { colors, shadows } from './theme.js';

export const appStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.canvas },
  safeArea: { flex: 1 },
  header: { minHeight: 78, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: colors.paper },
  identity: { flex: 1, minWidth: 0, flexDirection: 'row', alignItems: 'center', gap: 12 },
  avatar: { width: 50, height: 50, borderRadius: 18, borderWidth: 2, borderColor: colors.amber },
  identityCopy: { flex: 1, minWidth: 0 },
  greeting: { color: colors.muted, fontSize: 11, fontWeight: '600' },
  personName: { color: colors.maroonDark, fontSize: 17, fontWeight: '900', marginTop: 2 },
  headerActions: { flexDirection: 'row', gap: 6 },
  iconButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center', borderRadius: 13, backgroundColor: colors.softSaffron, position: 'relative' },
  notificationDot: { position: 'absolute', top: 7, right: 8, width: 7, height: 7, borderRadius: 4, backgroundColor: colors.saffron, borderWidth: 1, borderColor: colors.paper },
  page: { flex: 1 },
  scroll: { paddingHorizontal: 16, paddingTop: 10, paddingBottom: 112, width: '100%', maxWidth: 760, alignSelf: 'center' },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { color: colors.muted, fontSize: 12 },
  tabBar: { position: 'absolute', left: 0, right: 0, bottom: 0, minHeight: 76, paddingHorizontal: 7, paddingTop: 7, paddingBottom: 7, flexDirection: 'row', alignItems: 'stretch', backgroundColor: colors.maroon, borderTopLeftRadius: 22, borderTopRightRadius: 22, ...shadows.card },
  tab: { flex: 1, minWidth: 0, alignItems: 'center', justifyContent: 'center', gap: 3 },
  tabIcon: { width: 36, height: 31, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  tabIconActive: { backgroundColor: colors.cream },
  tabLabel: { color: 'rgba(255,255,255,.64)', fontSize: 9, fontWeight: '700' },
  tabLabelActive: { color: colors.paper, fontWeight: '900' },
  floatingHelp: { position: 'absolute', right: 18, bottom: 92, width: 54, height: 54, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.saffron, borderWidth: 3, borderColor: colors.paper, ...shadows.card },
  welcome: { flexGrow: 1, padding: 24, justifyContent: 'center', backgroundColor: colors.cream },
  welcomeLogo: { width: 112, height: 112, borderRadius: 28, borderWidth: 2, borderColor: colors.amber, marginBottom: 24 },
  welcomeEyebrow: { alignSelf: 'flex-start', color: colors.maroon, backgroundColor: colors.softSaffron, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, fontSize: 11, fontWeight: '800', marginBottom: 16 },
  welcomeTitle: { color: colors.maroonDark, fontSize: 34, lineHeight: 40, fontWeight: '900', letterSpacing: -1.2 },
  welcomeText: { color: colors.muted, fontSize: 15, lineHeight: 23, marginTop: 14, marginBottom: 24 },
  primaryButton: { minHeight: 54, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.maroon },
  primaryButtonText: { color: colors.paper, fontSize: 14, fontWeight: '900' },
  version: { color: colors.muted, fontSize: 9, textAlign: 'center', marginTop: 18 },
});
