import { StyleSheet } from 'react-native';
import { colors, shadows } from './theme.js';

export const appStyles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.canvas },
  safeArea: { flex: 1 },
  header: {
    minHeight: 64,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.paper,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.line,
  },
  brand: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 },
  logo: { width: 42, height: 42, borderRadius: 11, borderWidth: 1, borderColor: '#F0D983' },
  brandTitle: { color: colors.maroon, fontSize: 14, fontWeight: '800' },
  brandSubtitle: { color: colors.muted, fontSize: 9, fontWeight: '600', marginTop: 2 },
  profileButton: { width: 38, height: 38, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.softSaffron },
  profileInitial: { color: colors.maroon, fontSize: 14, fontWeight: '800' },
  page: { flex: 1 },
  scroll: { paddingHorizontal: 14, paddingTop: 16, paddingBottom: 104, width: '100%', maxWidth: 760, alignSelf: 'center' },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 },
  loadingText: { color: colors.muted, fontSize: 12 },
  tabBar: {
    position: 'absolute',
    left: 10,
    right: 10,
    bottom: 8,
    minHeight: 66,
    paddingHorizontal: 5,
    paddingVertical: 5,
    flexDirection: 'row',
    alignItems: 'stretch',
    backgroundColor: 'rgba(255,255,255,0.98)',
    borderWidth: 1,
    borderColor: colors.line,
    borderRadius: 20,
    ...shadows.card,
  },
  tab: { flex: 1, minWidth: 0, borderRadius: 14, alignItems: 'center', justifyContent: 'center', gap: 3 },
  tabActive: { backgroundColor: colors.softSaffron },
  tabLabel: { color: colors.muted, fontSize: 9, fontWeight: '650' },
  tabLabelActive: { color: colors.maroon, fontWeight: '800' },
  moreBackdrop: { flex: 1, backgroundColor: 'rgba(36,25,26,.38)', justifyContent: 'flex-end' },
  moreSheet: { padding: 18, paddingBottom: 30, borderTopLeftRadius: 26, borderTopRightRadius: 26, backgroundColor: colors.paper },
  sheetHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 4, backgroundColor: colors.line, marginBottom: 18 },
  sheetTitle: { color: colors.maroonDark, fontSize: 20, fontWeight: '800', marginBottom: 14 },
  moreAction: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 12, paddingHorizontal: 14, borderRadius: 14, backgroundColor: colors.canvas, marginBottom: 10 },
  moreActionText: { flex: 1, color: colors.ink, fontSize: 14, fontWeight: '700' },
  signOutAction: { backgroundColor: colors.softMaroon },
  welcome: { flexGrow: 1, padding: 22, justifyContent: 'center' },
  welcomeLogo: { width: 108, height: 108, borderRadius: 24, borderWidth: 2, borderColor: '#F0D983', marginBottom: 24 },
  welcomeEyebrow: { alignSelf: 'flex-start', color: colors.maroon, backgroundColor: colors.softSaffron, paddingHorizontal: 12, paddingVertical: 7, borderRadius: 999, fontSize: 11, fontWeight: '800', marginBottom: 16 },
  welcomeTitle: { color: colors.maroonDark, fontSize: 34, lineHeight: 40, fontWeight: '900', letterSpacing: -1.2 },
  welcomeText: { color: colors.muted, fontSize: 15, lineHeight: 23, marginTop: 14, marginBottom: 24 },
  primaryButton: { minHeight: 52, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.maroon },
  primaryButtonText: { color: colors.paper, fontSize: 14, fontWeight: '800' },
  version: { color: colors.muted, fontSize: 9, textAlign: 'center', marginTop: 18 },
});
