import React, { useEffect, useState } from 'react';
import { ActivityIndicator, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useMutation, useQuery } from '@apollo/client';
import { Ionicons } from '@expo/vector-icons';
import { DELETE_REMINDER_SCHEDULE_MUTATION, MARK_ALL_NOTIFICATIONS_READ_MUTATION, NOTIFICATION_CENTRE_QUERY, SAVE_REMINDER_SCHEDULE_MUTATION, SET_NOTIFICATION_STATUS_MUTATION, UPDATE_NOTIFICATION_PREFERENCES_MUTATION } from '../graphql/operations.js';
import { colors, shadows } from '../theme/theme.js';

export default function MobileNotificationCentre() {
  const { data, loading, error, refetch } = useQuery(NOTIFICATION_CENTRE_QUERY, { fetchPolicy:'cache-and-network' });
  const [mode,setMode]=useState('inbox'); const [prefs,setPrefs]=useState(null); const [label,setLabel]=useState(''); const [localTime,setLocalTime]=useState('08:00'); const [notice,setNotice]=useState('');
  const [setStatus]=useMutation(SET_NOTIFICATION_STATUS_MUTATION); const [markAll]=useMutation(MARK_ALL_NOTIFICATIONS_READ_MUTATION); const [updatePrefs]=useMutation(UPDATE_NOTIFICATION_PREFERENCES_MUTATION); const [saveReminder]=useMutation(SAVE_REMINDER_SCHEDULE_MUTATION); const [deleteReminder]=useMutation(DELETE_REMINDER_SCHEDULE_MUTATION);
  useEffect(()=>{if(data?.myNotificationPreferences){const {id,__typename,...value}=data.myNotificationPreferences;setPrefs(value);}},[data]);
  if(loading&&!data)return <ActivityIndicator color={colors.maroon}/>; if(error)return <Text style={s.empty}>Notification centre could not be loaded.</Text>;
  const inbox=data?.myNotifications;
  return <View style={s.screen}><Text style={s.eyebrow}>STAY CONNECTED</Text><Text style={s.heading}>Notifications & reminders</Text><View style={s.tabs}>{[['inbox',`Inbox ${inbox?.unreadCount||''}`],['preferences','Preferences'],['reminders','Reminders']].map(([value,text])=><TouchableOpacity key={value} style={[s.tab,mode===value&&s.tabActive]} onPress={()=>setMode(value)}><Text style={[s.tabText,mode===value&&s.tabTextActive]}>{text}</Text></TouchableOpacity>)}</View>{notice?<Text style={s.notice}>{notice}</Text>:null}
    {mode==='inbox'?<View style={s.stack}><TouchableOpacity disabled={!inbox?.unreadCount} style={s.secondary} onPress={async()=>{await markAll();refetch();}}><Text style={s.secondaryText}>Mark all read</Text></TouchableOpacity>{inbox?.items?.length?inbox.items.map((item)=><View key={item.id} style={[s.card,item.status==='unread'&&s.unread]}><View style={s.cardHead}><Ionicons name="notifications-outline" size={20} color={colors.maroon}/><Text style={s.title}>{item.title}</Text>{item.status==='unread'?<View style={s.dot}/>:null}</View><Text style={s.body}>{item.body}</Text><Text style={s.meta}>{new Date(item.createdAt).toLocaleString()}</Text><View style={s.actions}>{item.status==='unread'?<TouchableOpacity onPress={async()=>{await setStatus({variables:{id:item.id,status:'read'}});refetch();}}><Text style={s.link}>Mark read</Text></TouchableOpacity>:null}<TouchableOpacity onPress={async()=>{await setStatus({variables:{id:item.id,status:'archived'}});refetch();}}><Text style={s.link}>Archive</Text></TouchableOpacity></View></View>):<Text style={s.empty}>You are all caught up.</Text>}</View>:null}
    {mode==='preferences'&&prefs?<View style={s.card}><Text style={s.title}>Delivery preferences</Text>{[['pushEnabled','Push notifications'],['emailEnabled','Email updates'],['whatsappEnabled','WhatsApp reminders'],['marketingAllowed','Optional marketing']].map(([key,text])=><View style={s.pref} key={key}><Text style={s.body}>{text}</Text><Switch value={Boolean(prefs[key])} onValueChange={(value)=>setPrefs({...prefs,[key]:value})} trackColor={{true:colors.saffron}}/></View>)}<TextInput style={s.input} value={prefs.quietStart||''} placeholder="Quiet starts 22:00" onChangeText={(quietStart)=>setPrefs({...prefs,quietStart:quietStart||null})}/><TextInput style={s.input} value={prefs.quietEnd||''} placeholder="Quiet ends 07:00" onChangeText={(quietEnd)=>setPrefs({...prefs,quietEnd:quietEnd||null})}/><TouchableOpacity style={s.primary} onPress={async()=>{await updatePrefs({variables:{input:prefs}});setNotice('Preferences saved.');refetch();}}><Text style={s.primaryText}>Save preferences</Text></TouchableOpacity></View>:null}
    {mode==='reminders'?<View style={s.stack}><View style={s.card}><Text style={s.title}>Create daily reminder</Text><TextInput style={s.input} value={label} placeholder="Morning practice" onChangeText={setLabel}/><TextInput style={s.input} value={localTime} placeholder="08:00" onChangeText={setLocalTime}/><TouchableOpacity style={s.primary} onPress={async()=>{await saveReminder({variables:{input:{label,localTime,daysOfWeek:[0,1,2,3,4,5,6],channel:'push',enabled:true}}});setLabel('');setNotice('Reminder saved.');refetch();}}><Text style={s.primaryText}>Add reminder</Text></TouchableOpacity></View>{data?.myReminderSchedules?.map((item)=><View style={s.card} key={item.id}><View style={s.cardHead}><Ionicons name="time-outline" size={20} color={colors.maroon}/><Text style={s.title}>{item.label}</Text></View><Text style={s.body}>{item.localTime} · {item.channel}</Text><TouchableOpacity onPress={async()=>{await deleteReminder({variables:{id:item.id}});refetch();}}><Text style={s.delete}>Delete</Text></TouchableOpacity></View>)}</View>:null}
  </View>;
}
const s=StyleSheet.create({screen:{gap:12},eyebrow:{color:colors.saffron,fontSize:9,fontWeight:'900',letterSpacing:1},heading:{color:colors.maroonDark,fontSize:25,fontWeight:'900'},tabs:{flexDirection:'row',gap:6},tab:{flex:1,paddingVertical:10,borderRadius:12,backgroundColor:colors.paper,alignItems:'center',borderWidth:1,borderColor:colors.line},tabActive:{backgroundColor:colors.maroon},tabText:{fontSize:9,fontWeight:'900',color:colors.muted},tabTextActive:{color:colors.paper},stack:{gap:10},card:{padding:16,borderRadius:18,backgroundColor:colors.paper,borderWidth:1,borderColor:colors.line,...shadows.card},unread:{backgroundColor:'#fff8ea'},cardHead:{flexDirection:'row',alignItems:'center',gap:9},title:{flex:1,color:colors.maroonDark,fontSize:14,fontWeight:'900'},body:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:8},meta:{color:colors.muted,fontSize:8,marginTop:8},dot:{width:8,height:8,borderRadius:4,backgroundColor:colors.saffron},actions:{flexDirection:'row',gap:18,marginTop:12},link:{color:colors.maroon,fontSize:10,fontWeight:'900'},delete:{color:'#a33',fontSize:10,fontWeight:'900',marginTop:12},pref:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',paddingVertical:10,borderBottomWidth:1,borderBottomColor:colors.line},input:{marginTop:10,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:11,color:colors.maroonDark},primary:{marginTop:12,padding:13,borderRadius:13,alignItems:'center',backgroundColor:colors.maroon},primaryText:{color:colors.paper,fontWeight:'900',fontSize:11},secondary:{alignSelf:'flex-end',padding:9},secondaryText:{color:colors.maroon,fontSize:10,fontWeight:'900'},notice:{padding:10,borderRadius:12,color:colors.success,backgroundColor:'#edf8f0',fontSize:10,fontWeight:'800'},empty:{textAlign:'center',color:colors.muted,marginTop:25}});
