import { StyleSheet } from 'react-native';
import { colors, shadows } from '../theme/theme.js';

const baseStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  safeArea: {
    flex: 1,
  },
  centeredContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  header: {
    height: 70,
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(253, 224, 224, 0.6)',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 3,
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  logoBg: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    shadowColor: '#f97316',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 2,
  },
  logoEmoji: {
    fontSize: 16,
    color: '#fff',
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#ea580c',
  },
  headerSubtitle: {
    fontSize: 8,
    color: '#fb7185',
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginTop: 1,
  },
  headerRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerProfileTextContainer: {
    alignItems: 'flex-end',
    marginRight: 10,
    maxWidth: 120,
  },
  headerProfileName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1e293b',
  },
  headerProfileSub: {
    fontSize: 8,
    color: '#fb7185',
    fontWeight: '600',
    marginTop: 1,
  },
  signOutIconButton: {
    padding: 6,
    borderRadius: 8,
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#ffe4e6',
  },
  signOutIconText: {
    fontSize: 14,
  },
  headerSignInButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#f97316',
  },
  headerSignInButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '700',
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 85, // Extra space to clear tab bar
  },
  signedOutScrollContent: {
    flexGrow: 1,
    justifyContent: 'center',
    padding: 16,
  },
  greetingCard: {
    borderRadius: 24,
    padding: 24,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: '#ea580c',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 4,
  },
  greetingBabyEmoji: {
    fontSize: 100,
    opacity: 0.12,
    position: 'absolute',
    right: -10,
    bottom: -15,
  },
  greetingTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#fff',
  },
  greetingDesc: {
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 18,
    marginTop: 8,
    paddingRight: 40,
  },
  badgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  capsuleBadge: {
    backgroundColor: 'rgba(255, 255, 255, 0.22)',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  capsuleBadgeText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '600',
  },
  
  // Custom Card Layouts
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#fff1f2',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1e293b',
    marginBottom: 6,
  },
  cardDesc: {
    fontSize: 12,
    color: '#64748b',
    marginBottom: 10,
    lineHeight: 16,
  },
  emptyText: {
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 12,
    marginVertical: 20,
  },

  // Content calendar elements
  daySelectorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#f8fafc',
    padding: 12,
    borderRadius: 16,
    marginBottom: 16,
  },
  dayInput: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    width: 60,
    textAlign: 'center',
    padding: 8,
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1e293b',
  },
  dayInputLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748b',
  },
  dailyContentBox: {
    backgroundColor: '#fff1f2',
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: '#ffe4e6',
  },
  dailyCategory: {
    fontSize: 10,
    fontWeight: '800',
    color: '#f43f5e',
    letterSpacing: 1,
  },
  dailyTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1e293b',
    marginTop: 6,
  },
  dailyBody: {
    fontSize: 13,
    color: '#334155',
    lineHeight: 18,
    marginTop: 10,
  },
  mediaButton: {
    marginTop: 14,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#f97316',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  mediaButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#f97316',
  },

  // Library styling
  libraryCategoryTab: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  libraryCategoryTabActive: {
    backgroundColor: '#f97316',
    borderColor: '#f97316',
  },
  libraryCategoryText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748b',
  },
  libraryCategoryTextActive: {
    color: '#fff',
  },
  libraryItemCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#f1f5f9',
    borderRadius: 16,
    padding: 16,
  },
  libraryItemDay: {
    fontSize: 9,
    fontWeight: '850',
    color: '#f97316',
  },
  libraryItemTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1e293b',
    marginTop: 2,
  },
  libraryItemBody: {
    fontSize: 11,
    color: '#475569',
    marginTop: 6,
    lineHeight: 16,
  },
  libraryItemLink: {
    color: '#f97316',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 8,
  },

  // Baby tracker styling
  babyInfoBox: {
    backgroundColor: '#fffbeb',
    borderWidth: 1,
    borderColor: '#fef3c7',
    borderRadius: 16,
    padding: 16,
  },
  babyInfoWeek: {
    fontSize: 10,
    fontWeight: '850',
    color: '#d97706',
  },
  babyInfoSize: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1e293b',
    marginTop: 4,
  },
  babyInfoWeight: {
    fontSize: 13,
    color: '#d97706',
    fontWeight: '600',
    marginTop: 2,
  },
  babyDivider: {
    height: 1,
    backgroundColor: '#fef3c7',
    marginVertical: 12,
  },
  babyInfoLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: '#1e293b',
    marginBottom: 4,
  },
  babyInfoDesc: {
    fontSize: 12,
    color: '#475569',
    lineHeight: 17,
  },

  // Forum style sheets
  forumPostCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: '#f1f5f9',
  },
  forumPostUserRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  forumUserAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ffe4e6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  forumUserAvatarText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#f43f5e',
  },
  forumUserName: {
    fontSize: 11,
    fontWeight: '700',
    color: '#1e293b',
  },
  forumPostTime: {
    fontSize: 9,
    color: '#94a3b8',
  },
  forumPostTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1e293b',
  },
  forumPostBody: {
    fontSize: 12,
    color: '#475569',
    lineHeight: 16,
    marginTop: 6,
  },
  forumSubmitBtn: {
    marginTop: 8,
    backgroundColor: '#f97316',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
  },
  forumSubmitBtnText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  forumCommentSection: {
    marginTop: 14,
    borderTopWidth: 1,
    borderTopColor: '#f1f5f9',
    paddingTop: 12,
  },
  forumCommentCount: {
    fontSize: 11,
    fontWeight: '800',
    color: '#64748b',
    marginBottom: 6,
  },
  forumCommentItem: {
    backgroundColor: '#f8fafc',
    borderRadius: 10,
    padding: 8,
    marginBottom: 6,
  },
  forumCommentUser: {
    fontSize: 10,
    fontWeight: '700',
    color: '#334155',
  },
  forumCommentText: {
    fontSize: 11,
    color: '#475569',
    marginTop: 1,
  },
  forumCommentInputRow: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 8,
  },
  forumCommentInput: {
    flex: 1,
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#cbd5e1',
    borderRadius: 10,
    paddingHorizontal: 10,
    fontSize: 11,
  },
  forumCommentBtn: {
    backgroundColor: '#f43f5e',
    borderRadius: 10,
    paddingHorizontal: 12,
    justifyContent: 'center',
  },
  forumCommentBtnText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
  },

  // Live classes style sheets
  liveClassCard: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#fff1f2',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  liveClassTime: {
    fontSize: 10,
    fontWeight: '800',
    color: '#d97706',
    backgroundColor: '#fef3c7',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  liveClassTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#1e293b',
    marginTop: 6,
  },
  liveClassInstructor: {
    fontSize: 10,
    color: '#64748b',
    marginTop: 1,
  },
  liveClassBtnBook: {
    backgroundColor: '#f97316',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  liveClassBtnJoined: {
    backgroundColor: '#22c55e',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  liveClassBtnText: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '800',
  },

  // Settings elements
  checkoutBtn: {
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#ffe4e6',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  checkoutBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#f43f5e',
  },
  checkoutBtnGold: {
    backgroundColor: '#ea580c',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  checkoutBtnTextGold: {
    fontSize: 12,
    fontWeight: '800',
    color: '#fff',
  },
  premiumBadgeBox: {
    backgroundColor: '#f0fdf4',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    borderRadius: 12,
    padding: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  premiumBadgeText: {
    color: '#166534',
    fontSize: 11,
    fontWeight: '800',
  },

  // Guides Card
  guidesCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: '#fff1f2',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.04,
    shadowRadius: 10,
    elevation: 1,
  },
  guidesCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  guidesCardHeaderEmoji: {
    fontSize: 24,
    marginRight: 10,
  },
  guidesCardHeaderTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1e293b',
  },
  guidesCardHeaderDesc: {
    fontSize: 11,
    color: '#64748b',
    marginTop: 1,
  },
  guideRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  guideRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  guideName: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1e293b',
  },
  guideRoleOrange: {
    fontSize: 10,
    color: '#f97316',
    fontWeight: '600',
    marginTop: 2,
  },
  guideRoleRose: {
    fontSize: 10,
    color: '#f43f5e',
    fontWeight: '600',
    marginTop: 2,
  },
  chatButtonOrange: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: '#fff7ed',
    borderWidth: 1,
    borderColor: '#ffedd5',
  },
  chatButtonRose: {
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#ffe4e6',
  },
  chatButtonText: {
    fontSize: 11,
    fontWeight: '750',
    color: '#1e293b',
  },
  affirmationCard: {
    borderRadius: 24,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 3,
  },
  affirmationLabel: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 1.5,
    opacity: 0.8,
  },
  affirmationQuote: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '600',
    fontStyle: 'italic',
    textAlign: 'center',
    lineHeight: 20,
    marginTop: 10,
  },

  // Onboarding styles
  onboardingCard: {
    backgroundColor: '#ffffff',
    borderRadius: 24,
    padding: 24,
    margin: 16,
    borderWidth: 1,
    borderColor: '#fff1f2',
    elevation: 2,
  },
  onboardingTitle: {
    fontSize: 20,
    fontWeight: '850',
    color: '#1e293b',
    textAlign: 'center',
  },
  onboardingSub: {
    fontSize: 12,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 20,
  },
  onboardingLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#475569',
    marginBottom: 6,
    textTransform: 'uppercase',
  },
  onboardingInput: {
    backgroundColor: '#f8fafc',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 13,
    color: '#1e293b',
    marginBottom: 14,
  },
  onboardingDivider: {
    textAlign: 'center',
    color: '#94a3b8',
    fontSize: 11,
    marginBottom: 14,
  },
  langSelectorRow: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 20,
  },
  langSelectorBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: '#f1f5f9',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  langSelectorBtnActive: {
    backgroundColor: '#f97316',
    borderColor: '#f97316',
  },
  langSelectorBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748b',
  },
  langSelectorBtnTextActive: {
    color: '#fff',
  },
  onboardingSubmitBtn: {
    borderRadius: 16,
    overflow: 'hidden',
  },

  // Tab bar styling
  tabBar: {
    height: 60,
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    elevation: 8,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabIcon: {
    fontSize: 16,
    color: '#94a3b8',
  },
  tabLabel: {
    fontSize: 9,
    fontWeight: '700',
    color: '#94a3b8',
    marginTop: 2,
  },
  tabActiveText: {
    color: '#f97316',
  },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(30, 41, 59, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    padding: 24,
    maxHeight: '90%',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1e293b',
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 12,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 20,
  },
  errorBox: {
    backgroundColor: '#fff1f2',
    borderWidth: 1,
    borderColor: '#ffe4e6',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
  },
  errorBoxText: {
    color: '#e11d48',
    fontSize: 11,
    fontWeight: '600',
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: '#475569',
    marginBottom: 6,
  },
  textInput: {
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 13,
    color: '#1e293b',
    marginBottom: 16,
    backgroundColor: '#f8fafc',
  },
  submitButton: {
    borderRadius: 24,
    overflow: 'hidden',
    marginTop: 6,
    marginBottom: 12,
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 2,
  },
  submitButtonGradient: {
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '800',
  },
  cancelButton: {
    alignItems: 'center',
    paddingVertical: 10,
  },
  cancelButtonText: {
    color: '#64748b',
    fontSize: 13,
    fontWeight: '700',
  },
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 14,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e2e8f0',
  },
  dividerText: {
    marginHorizontal: 10,
    color: '#94a3b8',
    fontSize: 12,
    fontWeight: '600',
  },
  googleButton: {
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    backgroundColor: '#ffffff',
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  googleButtonText: {
    color: '#1e293b',
    fontSize: 13,
    fontWeight: '800',
  },
  welcomeContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
  },
  welcomeBadge: {
    backgroundColor: '#ffe4e6',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 20,
  },
  welcomeBadgeText: {
    color: '#f43f5e',
    fontSize: 10,
    fontWeight: '750',
    letterSpacing: 1,
  },
  welcomeTitle: {
    fontSize: 32,
    fontWeight: '900',
    color: '#1e293b',
    textAlign: 'center',
    lineHeight: 40,
    marginBottom: 16,
  },
  welcomeTitleHighlight: {
    color: '#ea580c',
  },
  welcomeDesc: {
    fontSize: 14,
    color: '#475569',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 30,
    paddingHorizontal: 10,
  },
  welcomeButton: {
    width: '100%',
    borderRadius: 28,
    overflow: 'hidden',
    shadowColor: '#f43f5e',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 4,
  },
  welcomeButtonGradient: {
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
  logoImage: {
    width: 38,
    height: 38,
    borderRadius: 19,
    marginRight: 10,
    borderWidth: 1,
    borderColor: 'rgba(253, 224, 224, 0.6)',
  },
});

const refreshedStyles = StyleSheet.create({
  card: { backgroundColor: colors.paper, borderRadius: 18, padding: 18, borderWidth: 1, borderColor: colors.line, ...shadows.card },
  cardTitle: { fontSize: 17, lineHeight: 23, fontWeight: '800', color: colors.maroonDark, marginBottom: 6 },
  cardDesc: { fontSize: 12, color: colors.muted, marginBottom: 10, lineHeight: 18 },
  emptyText: { textAlign: 'center', color: colors.muted, fontSize: 12, marginVertical: 24 },
  greetingCard: { borderRadius: 20, padding: 22, position: 'relative', overflow: 'hidden', ...shadows.card },
  daySelectorRow: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: colors.canvas, padding: 12, borderRadius: 14, marginBottom: 16 },
  dayInput: { backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, borderRadius: 10, width: 64, textAlign: 'center', padding: 9, fontSize: 14, fontWeight: 'bold', color: colors.ink },
  dayInputLabel: { fontSize: 12, fontWeight: '600', color: colors.muted },
  dailyContentBox: { backgroundColor: colors.softSaffron, borderRadius: 15, padding: 16, borderWidth: 1, borderColor: '#F2DFB7' },
  dailyCategory: { fontSize: 10, fontWeight: '800', color: colors.maroon, letterSpacing: 1 },
  dailyTitle: { fontSize: 16, fontWeight: '800', color: colors.maroonDark, marginTop: 6 },
  dailyBody: { fontSize: 13, color: colors.ink, lineHeight: 19, marginTop: 10 },
  mediaButton: { marginTop: 14, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.saffron, borderRadius: 11, paddingVertical: 11, alignItems: 'center' },
  mediaButtonText: { fontSize: 12, fontWeight: '800', color: colors.maroon },
  libraryCategoryTab: { paddingHorizontal: 15, paddingVertical: 9, borderRadius: 999, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line },
  libraryCategoryTabActive: { backgroundColor: colors.maroon, borderColor: colors.maroon },
  libraryCategoryText: { fontSize: 11, fontWeight: '700', color: colors.muted },
  libraryCategoryTextActive: { color: colors.paper },
  libraryItemCard: { backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, borderRadius: 15, padding: 16 },
  libraryItemDay: { fontSize: 9, fontWeight: '800', color: colors.saffron },
  libraryItemTitle: { fontSize: 14, fontWeight: '800', color: colors.maroonDark, marginTop: 3 },
  libraryItemBody: { fontSize: 12, color: colors.muted, marginTop: 7, lineHeight: 17 },
  libraryItemLink: { color: colors.maroon, fontSize: 11, fontWeight: '800', marginTop: 9 },
  babyInfoBox: { backgroundColor: colors.softSaffron, borderWidth: 1, borderColor: '#F2DFB7', borderRadius: 16, padding: 18 },
  babyInfoWeek: { fontSize: 10, fontWeight: '800', color: colors.maroon },
  babyInfoSize: { fontSize: 19, fontWeight: '800', color: colors.maroonDark, marginTop: 4 },
  babyInfoWeight: { fontSize: 13, color: colors.saffron, fontWeight: '700', marginTop: 2 },
  babyDivider: { height: 1, backgroundColor: '#E9D29E', marginVertical: 14 },
  babyInfoLabel: { fontSize: 12, fontWeight: '800', color: colors.ink, marginBottom: 4 },
  babyInfoDesc: { fontSize: 12, color: colors.muted, lineHeight: 18 },
  forumPostCard: { backgroundColor: colors.paper, borderRadius: 18, padding: 17, borderWidth: 1, borderColor: colors.line, ...shadows.card },
  forumUserAvatar: { width: 34, height: 34, borderRadius: 11, backgroundColor: colors.softSaffron, alignItems: 'center', justifyContent: 'center' },
  forumUserAvatarText: { fontSize: 12, fontWeight: '800', color: colors.maroon },
  forumPostTitle: { fontSize: 15, fontWeight: '800', color: colors.maroonDark },
  forumPostBody: { fontSize: 12, color: colors.muted, lineHeight: 17, marginTop: 6 },
  forumSubmitBtn: { marginTop: 8, backgroundColor: colors.maroon, borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  forumCommentItem: { backgroundColor: colors.canvas, borderRadius: 10, padding: 9, marginBottom: 6 },
  forumCommentInput: { flex: 1, backgroundColor: colors.canvas, borderWidth: 1, borderColor: colors.line, borderRadius: 10, paddingHorizontal: 10, fontSize: 11 },
  forumCommentBtn: { backgroundColor: colors.saffron, borderRadius: 10, paddingHorizontal: 12, justifyContent: 'center' },
  liveClassCard: { backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, borderRadius: 15, padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12 },
  liveClassTime: { fontSize: 10, fontWeight: '800', color: colors.maroon, backgroundColor: colors.softSaffron, paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, alignSelf: 'flex-start' },
  liveClassTitle: { fontSize: 13, fontWeight: '800', color: colors.maroonDark, marginTop: 6 },
  liveClassInstructor: { fontSize: 10, color: colors.muted, marginTop: 2 },
  liveClassBtnBook: { backgroundColor: colors.maroon, borderRadius: 11, paddingHorizontal: 16, paddingVertical: 10 },
  liveClassBtnJoined: { backgroundColor: colors.success, borderRadius: 11, paddingHorizontal: 14, paddingVertical: 10 },
  checkoutBtnGold: { marginTop: 12, backgroundColor: colors.sun, borderWidth: 1, borderColor: colors.amber, borderRadius: 12, paddingVertical: 12, alignItems: 'center' },
  checkoutBtnTextGold: { color: colors.maroonDark, fontSize: 12, fontWeight: '800' },
  premiumBadgeBox: { backgroundColor: '#EBF7F0', borderWidth: 1, borderColor: '#B9DEC9', borderRadius: 12, padding: 12, marginTop: 12 },
  guidesCard: { backgroundColor: colors.paper, borderRadius: 18, borderWidth: 1, borderColor: colors.line, overflow: 'hidden', ...shadows.card },
  guidesCardHeader: { backgroundColor: colors.maroon, padding: 18 },
  guideName: { fontSize: 13, fontWeight: '800', color: colors.maroonDark },
  guideRoleOrange: { fontSize: 10, color: colors.saffron, fontWeight: '700', marginTop: 2 },
  guideRoleRose: { fontSize: 10, color: colors.maroon, fontWeight: '700', marginTop: 2 },
  chatButtonOrange: { backgroundColor: colors.maroon, borderRadius: 10, paddingVertical: 8, paddingHorizontal: 15 },
  chatButtonRose: { backgroundColor: colors.saffron, borderRadius: 10, paddingVertical: 8, paddingHorizontal: 15 },
  onboardingCard: { flex: 1, alignSelf: 'center', width: '100%', maxWidth: 560, justifyContent: 'center', backgroundColor: colors.paper, margin: 16, padding: 22, borderRadius: 20, borderWidth: 1, borderColor: colors.line, ...shadows.card },
  onboardingTitle: { fontSize: 23, fontWeight: '900', color: colors.maroonDark, textAlign: 'center' },
  onboardingSub: { fontSize: 12, color: colors.muted, textAlign: 'center', lineHeight: 18, marginTop: 6, marginBottom: 22 },
  onboardingLabel: { fontSize: 11, fontWeight: '800', color: colors.maroonDark, marginBottom: 7, marginTop: 12 },
  onboardingInput: { minHeight: 48, backgroundColor: colors.paper, borderWidth: 1, borderColor: colors.line, borderRadius: 12, paddingHorizontal: 14, justifyContent: 'center', color: colors.ink, fontSize: 13 },
  onboardingDivider: { color: colors.muted, textAlign: 'center', marginVertical: 14, fontSize: 11 },
  langSelectorBtn: { flex: 1, paddingVertical: 11, borderRadius: 11, borderWidth: 1, borderColor: colors.line, alignItems: 'center', backgroundColor: colors.paper },
  langSelectorBtnActive: { backgroundColor: colors.maroon, borderColor: colors.maroon },
  langSelectorBtnText: { color: colors.muted, fontSize: 11, fontWeight: '700' },
  langSelectorBtnTextActive: { color: colors.paper },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(36,25,26,.48)', justifyContent: 'flex-end' },
  modalContent: { backgroundColor: colors.paper, borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 22, paddingBottom: 30 },
  modalTitle: { fontSize: 22, fontWeight: '900', color: colors.maroonDark, textAlign: 'center' },
  modalSubtitle: { fontSize: 12, color: colors.muted, textAlign: 'center', marginTop: 6, marginBottom: 20 },
  inputLabel: { color: colors.maroonDark, fontSize: 11, fontWeight: '800', marginBottom: 6, marginTop: 12 },
  textInput: { minHeight: 48, borderWidth: 1, borderColor: colors.line, borderRadius: 12, paddingHorizontal: 14, color: colors.ink, backgroundColor: colors.paper },
  submitButton: { marginTop: 18, borderRadius: 12, overflow: 'hidden', backgroundColor: colors.maroon },
  submitButtonGradient: { paddingVertical: 14, alignItems: 'center', backgroundColor: colors.maroon },
  googleButton: { minHeight: 48, borderWidth: 1, borderColor: colors.line, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.paper },
});

export const styles = { ...baseStyles, ...refreshedStyles };
